version: "3"

services:
  db:
    image: postgres
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"

volumes:
  postgres:
